-- DeskSharing initial PostgreSQL schema
-- Flyway migration: V1

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    entra_oid VARCHAR(255) NOT NULL,
    last_login_at TIMESTAMP(6) WITHOUT TIME ZONE,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT uq_app_user_entra_oid UNIQUE (entra_oid),
    CONSTRAINT ck_app_user_role
        CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE office (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL,
    description VARCHAR(1000),
    layout_height INTEGER NOT NULL,
    layout_width INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_office PRIMARY KEY (id)
);

CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL,
    description VARCHAR(1000),
    layout_height INTEGER NOT NULL,
    layout_width INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    pos_x INTEGER,
    pos_y INTEGER,
    office_id BIGINT,

    CONSTRAINT pk_room PRIMARY KEY (id),
    CONSTRAINT fk_room_office
        FOREIGN KEY (office_id)
        REFERENCES office (id)
);

CREATE TABLE resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL,
    bookable BOOLEAN NOT NULL,
    description VARCHAR(1000),
    height INTEGER,
    name VARCHAR(255) NOT NULL,
    pos_x INTEGER,
    pos_y INTEGER,
    resource_type VARCHAR(255) NOT NULL,
    width INTEGER,
    room_id BIGINT NOT NULL,

    CONSTRAINT pk_resource PRIMARY KEY (id),
    CONSTRAINT ck_resource_type
        CHECK (resource_type IN ('DESK', 'MEETING_ROOM')),
    CONSTRAINT fk_resource_room
        FOREIGN KEY (room_id)
        REFERENCES room (id)
);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_date_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    notes VARCHAR(1000),
    start_date_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    app_user_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,

    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CONSTRAINT ck_reservation_status
        CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT fk_reservation_app_user
        FOREIGN KEY (app_user_id)
        REFERENCES app_user (id),
    CONSTRAINT fk_reservation_resource
        FOREIGN KEY (resource_id)
        REFERENCES resource (id)
);

CREATE INDEX idx_room_office_id
    ON room (office_id);

CREATE INDEX idx_resource_room_id
    ON resource (room_id);

CREATE INDEX idx_reservation_app_user_id
    ON reservation (app_user_id);

CREATE INDEX idx_reservation_resource_id
    ON reservation (resource_id);

